### ISSUE TITLE
Piepmatz is crashing (specific tweet?)

### ISSUE THREAD

**Issue by Karry** [Wunderfitz/harbour-piepmatz#92]
Hi. 

Piepmatz start crashing for me (on SFOS 3.3). It seems to be caused by specific tweet, but I am unable to get more details with gdb. Here is tail from log and few lines from debugger (with installed qt debug symbols):
```
...
[D] expression for onUserTimelineSuccessful:93 - Timeline updated for user KarryCZ
[New Thread 0xaab64310 (LWP 7915)]
[New Thread 0xaa404310 (LWP 7916)]
[W] unknown:86 - file:///usr/share/harbour-piepmatz/qml/components/User.qml:86:21: QML Image: Error transferring https://pbs.twimg.com/profile_images/1135549310228193281/OD8qSkC1_bigger.png - server replied: Not Found
[D] unknown:0 - TwitterApi::handleGetOpenGraphFinished
[D] unknown:0 - Open Graph content type header:  "text/html; charset=Off"
[D] unknown:0 - Available Open Graph charset:  "OFF"
[D] unknown:0 - Open Graph Charset for  "https://www.earchiv.cz/a93/a324c200.php3" :  "OFF"

Thread 1 "harbour-piepmat" received signal SIGSEGV, Segmentation fault.
0xb63b3d92 in QTextCodec::toUnicode (this=0x0, a=...) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:430
430     ../../include/QtCore/../../src/corelib/tools/qbytearray.h: No such file or directory.
(gdb) bt
#0  0xb63b3d92 in QTextCodec::toUnicode (this=0x0, a=...) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:430
#1  0x2a05f568 in _start ()
(gdb) bt full
#0  0xb63b3d92 in QTextCodec::toUnicode (this=0x0, a=...) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:430
No locals.
#1  0x2a05f568 in _start ()
No symbol table info available.
(gdb) info threads
  Id   Target Id                                      Frame 
* 1    Thread 0xb3a68790 (LWP 7511) "harbour-piepmat" 0xb63b3d92 in QTextCodec::toUnicode (this=0x0, a=...) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:430
  2    Thread 0xb2ccc310 (LWP 7660) "QQmlThread"      __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  3    Thread 0xb20ff310 (LWP 7661) "Qt bearer threa" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  4    Thread 0xb1cff310 (LWP 7665) "QDBusConnection" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  5    Thread 0xb1744310 (LWP 7704) "dconf worker"    __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  6    Thread 0xb13ff310 (LWP 7705) "gmain"           __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  7    Thread 0xb0fff310 (LWP 7706) "gdbus"           __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  8    Thread 0xaf10d310 (LWP 7776) "GL updater"      __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  10   Thread 0xaed5f310 (LWP 7778) "QSGRenderThread" 0xb329f1a0 in ?? ()
  11   Thread 0xadbd3310 (LWP 7781) "NemoThumbnailLo" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  12   Thread 0xad9d2310 (LWP 7782) "Qt HTTP thread"  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  13   Thread 0xad7d1310 (LWP 7783) "Thread (pooled)" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  14   Thread 0xad408310 (LWP 7785) "GL updater"      __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  16   Thread 0xad14d310 (LWP 7792) "QSGRenderThread" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  17   Thread 0xac50f310 (LWP 7806) "QQuickPixmapRea" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  18   Thread 0xac30e310 (LWP 7807) "Qt HTTP thread"  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  19   Thread 0xaab64310 (LWP 7915) "Thread (pooled)" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  20   Thread 0xaa404310 (LWP 7916) "Thread (pooled)" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
```
It is enough info for reproduce the crash? Or should I build piepmatz with debug symbols and dig deeper? It is caused by "https://www.earchiv.cz/a93/a324c200.php3" page?

**Comment by Karry** [comment]
I am able to workaround crash with blocking that specific domain:
```
echo 127.0.0.1 www.earchiv.cz >> /etc/hosts
```

**Comment by Karry** [comment]
It appears again...
```
[D] unknown:0 - TwitterApi::getOpenGraph "https://qt.eu/engage/jobs/quantum-detector-scientist/"
[D] unknown:0 - TwitterApi::handleGetOpenGraphFinished
[D] unknown:0 - Open Graph content type header:  "text/html; charset=none"
[D] unknown:0 - Available Open Graph charset:  "NONE"
[D] unknown:0 - Open Graph Charset for  "https://qt.eu/engage/jobs/quantum-detector-scientist/" :  "NONE"
Segmentation fault (core dumped)
```

**Comment by Wunderfitz** [comment]
Reproducible with tweet https://twitter.com/QuantumFlagship/status/1308713988000305158

**Comment by Wunderfitz** [comment]
Thanks, seems to be fixed. Thanks for the PR! :) Version 1.7.1 will be online shortly.
